{
 "title": "Nginx Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Waiting" },
    { "expr": "nginx_connections_reading", "legendFormat": "Reading" },
    { "expr": "nginx_connections_writing", "legendFormat": "Writing" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{status=\"200\"}[1m])",
     "legendFormat": "200 OK"
    },
    {
     "expr": "rate(flask_http_request_total{status=\"404\"}[1m])",
     "legendFormat": "404 Not Found"
    },
    {
     "expr": "rate(flask_http_request_total{status=\"500\"}[1m])",
     "legendFormat": "500 Error"
    },
    {
     "expr": "rate(flask_http_request_total{status=\"503\"}[1m])",
     "legendFormat": "503 Unavailable"
    }
   ]
  }
 ]
}